### ISSUE TITLE
i want to contribute to the project

### ISSUE THREAD

**Issue by hoangchungk53qx1** [LNMCode/LNSocial-TiktokClone#2]
I want to contribute to the project, show me the backend system

**Comment by LNMCode** [comment]
Thanks for contacting to me. @hoangchungk53qx1 
I'm updating for the project, so I'll add you to the project to contribute early next week *(Monday, May 16)*.
I’ll send you backend information via your email at that time

**Comment by hoangchungk53qx1** [comment]
oke, sound good !. <3
