### ISSUE TITLE
When we add a comment the seed are reloading completely 

### ISSUE THREAD

**Issue by avinash1203** [LNMCode/LNSocial-TiktokClone#3]
When we add a comment. entire seeds are reloading how can i change this behavior? so that i can got the video which has been commented. and play the next video 

Please help me how can i fix it

**Comment by LNMCode** [comment]
Hi @avinash1203 
Thank you for your comment.

The server of the app is currently having problems and is not working, so temporarily the app will not work properly.
I will take care of it and get it back to normal as soon as possible.

Having nice day!

👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻

**Comment by avinash1203** [comment]
No I'm developing my own server but the problem with the Android app. When we write a comment and come back to seed. the app is showing the videos from 0th position and reloading the seeds  can you please suggest how can i fix it please i really really need it

**Comment by LNMCode** [comment]
Hi @avinash1203 
Sorry for your misunderstanding.

Is your comment screen in another fragment or activity?
if you have this problem, i think u can use modal bottom sheet instead of switching to another screen.

So, if u want to use fragment or activity, u can save data of seeds, position_current was loading before switching to another screen, and reloading them when u comeback. If u are worried about out of memory when many data of seeds, u can just save id of them.

Having nice day!
👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻

**Comment by avinash1203** [comment]
I'm using this repository as my android app. And in this repository we are using a new fragment to display comments. I can't save the position. Because when we recreate a view mobile then i will get random videos again. 

So is there any other way to just save the state of my seed fragment and use that to continue with my video scrolling in seed fragment

**Comment by LNMCode** [comment]
Hi @avinash1203 
Maybe i think u need to change from using another fragment to using modal bottom sheet or standard bottom sheet
Standard bottom sheet: https://m2.material.io/components/sheets-bottom/android#standard-bottom-sheet
Modal bottom sheet: https://m2.material.io/components/sheets-bottom/android#modal-bottom-sheet

Something like this for comment view:
![image](https://github.com/LNMCode/LNSocial-TiktokClone/assets/81409319/3035ff10-2163-45e5-ad43-5bd5f46d6671)


It will not recreate when u back seed view.
Having nice day!
👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻

**Comment by LNMCode** [comment]
Hi @avinash1203 
You can change it to modal bottom sheet, it maybe not recreate view when u comeback

**Comment by avinash1203** [comment]
Thank for the reply i have implemented it and it's working as expected

**Comment by LNMCode** [comment]
Hi @avinash1203 
Congratulation!
Ill close this issue.

Happy to help you!!

Having nice day!
👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻👨‍💻
